apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: chat-app
  labels:
    app: backend-deployment
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics" # Metrics endpoint
    prometheus.io/port: "5000"
spec:
  selector:
    app: backend-deployment
  ports:
    - port: 5000
      targetPort: 5000
