apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret
  namespace: chat-app
stringData:
  mongo-root-password: rootpassword
  mongo-uri: mongodb://zsm3084:rootpassword@mongodb-service.chat-app.svc.cluster.local:27017/chat-app?authSource=admin
  jwt-secret: chat-app-secret-key
  cloud-name: ""
  cloud-api-key: ""
  cloud-api-secret: ""
